version: '3.8'

services:
  # DynamoDB Local
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: five-bomber-dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    volumes:
      - ./dynamodb-data:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal

  # Lambda Runtime Interface Emulator - POST /api/rooms
  lambda-rooms-create:
    build: .
    container_name: five-bomber-lambda-rooms-create
    ports:
      - "9000:8080"
    environment:
      - DYNAMODB_ROOMS_TABLE=five-bomber-rooms-local
      - AWS_REGION=ap-northeast-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
    command: ["dist/handlers/rest/rooms.handler"]
    depends_on:
      - dynamodb-local

  # 将来的に追加するLambda関数はここに追加
  # lambda-rooms-get:
  #   build: .
  #   container_name: five-bomber-lambda-rooms-get
  #   ports:
  #     - "9001:8080"
  #   environment:
  #     - DYNAMODB_ROOMS_TABLE=five-bomber-rooms-local
  #     - AWS_REGION=ap-northeast-1
  #     - AWS_ACCESS_KEY_ID=dummy
  #     - AWS_SECRET_ACCESS_KEY=dummy
  #     - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
  #   command: ["dist/handlers/rest/rooms-get.handler"]
  #   depends_on:
  #     - dynamodb-local
